# astype()

### In Python (specifically using libraries like pandas or NumPy), astype() is a method used to cast or convert a data structure's data type from one type to another.

In [3]:
import numpy as np
arr=np.array([1.2,2.5,3.8])
print(arr)
print(arr.dtype)
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[1.2 2.5 3.8]
float64
[1 2 3]
int64


In [7]:
arr=np.array([10,20,30])
print(arr+5)
print(arr*2)
print(arr**2)
print(arr[2]*3)


[15 25 35]
[20 40 60]
[100 400 900]
90


In [14]:
print(np.sum(arr) )# add all elements
print(np.mean(arr)) # find the average
print(np.min(arr) )# find minimum value of the array
print(np.max(arr) )# find max value of the array
print(np.std(arr)) # find standard deviation 
print(np.var(arr)) # find variants
print(np.mod(arr))
print(np.median(arr))

60
20.0
10
30
8.16496580927726
66.66666666666667


TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given